// <auto-generated />
namespace PrintumCommerce.Migrations.DBPrintumContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class End : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(End));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161629198_End"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
